### ISSUE TITLE
Failure running InputB.GED

### ISSUE THREAD

**Issue by kroseberry13SIT** [karell/stevens_cs555#48]
Traceback (most recent call last):
  File "gedcom_parser.py", line 163, in <module>
    if checkMaleLastNames(j, indiObjHusband.lastname) == True:
  File "gedcom_parser.py", line 45, in checkMaleLastNames
    if child.gender == "M":
AttributeError: 'NoneType' object has no attribute 'gender'
PS C:\Users\klros\Google Drive\Keith\Stevens Institute of Technology\SSW-555-WS\gedcom\stevens_cs555\src>

**Comment by kroseberry13SIT** [comment]
The same error happens with Proj02Test.GED

**Comment by beacher101** [comment]
issue occurred when an individual has a child with an id, but the child doesn't exist in the dictionary.  Added a check to make sure the key exists in the dictionary before getting it and assigning it to the child

**Comment by beacher101** [comment]
all test files now execute properly
