### ISSUE TITLE
Check try..except for Age > 150 test

### ISSUE THREAD

**Issue by kroseberry13SIT** [karell/stevens_cs555#49]
The US7 code in individual.py to check for an age > 150 years is using a try..except block to return either the age or False. The statement in the try block shouldn't ever fail as it's returning a class variable; therefore, the except block will never be executed. Probably best to revert to a simple if statement to handle this.

When the return value of False is provided to the caller, this will result in "False" being displayed in the pretty table for the individual's age (I'm assuming).

**Comment by beacher101** [comment]
removed try block
